version: "3.9"
    
services:
  nginx:
    image: nginx:1.27.1
    container_name: nginx
    volumes:
       - wordpress_data:/var/www/html
       - ./content:/var/www/html/wp-content
       - ./nginx.conf:/etc/nginx/conf.d/wordpress.conf:ro
       - ./certs:/etc/nginx/certs:ro
    ports: 
      - 443:443
    restart: always
  db:
    image: mysql:8.0.39
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: wordpress_local
      MYSQL_USER: wordpress_db_user
      MYSQL_PASSWORD: wordpress_db_password   
  wordpress:
    depends_on:
      - db
    image: wordpress:fpm-alpine
    volumes:
      - wordpress_data:/var/www/html
      - ./content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_db_user
      WORDPRESS_DB_PASSWORD: wordpress_db_password
      WORDPRESS_DB_NAME: wordpress_local
  node_exporter:
    image: prom/node-exporter:v1.8.2
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
volumes:
  db_data: {}
  wordpress_data: {}