global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scheme: http
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'blackbox'
    scheme: http
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['blackbox_exporter:9115']

  - job_name: 'mysql'
    scheme: http
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'node'
    scheme: http
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['node_exporter:9100']